Add patch to fix libkj const errors build with GCC 9.3
We add two patches:
- patch for libkj
- patch for libtiledb to apply the libkj patch from the conda RECIPE_DIR before building

Build fails with:
```
$SRC_DIR/build/externals/src/ep_capnp/c++/src/kj/main.c++:690:38:   required from here
$BUILD_PREFIX/x86_64-conda-linux-gnu/include/c++/9.3.0/bits/stl_tree.h:780:8: error: static assertion failed: comparison object must be invocable as const
```